[project]
name = "agent-memory"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "agno>=2.2.13",
    "chromadb>=1.3.5",
    "google-genai>=1.51.0",
    "mem0ai>=1.0.1",
    "streamlit>=1.51.0",
]
